name: check lint in python code

on:
 push:
  branches:
    - main 
  paths:
    - 'main/*.py'

jobs:
 Lint:
  runs-on: ubuntu-latest
  steps:
    - name: checkout/gitclone
      uses: actions/checkout@v7
      
    - name: python install ruff
      run: pip install ruff

    - name: fix code automatically 
      run: ruff check --fix .
      
    - name: check code
      run: ruff check . 

  
    
 
 
     
